---

- name: Deploy petclinic
  gather_facts: false
  hosts: server1
  tasks:
    - name: Copying the Directory and its contents
      become: true 
      copy:
        src: /var/lib/jenkins/workspace/spring-petclinic_main/artifact/target/spring-petclinic-2.6.0-SNAPSHOT.jar
        dest: /home/vagrant/devops/spring-petclinic/artifact/spring-petclinic-2.6.0-SNAPSHOT.jar

    - name: Run jar application
      shell: nohup java -Dserver.port=8888 -jar /home/vagrant/devops/spring-petclinic/spring-petclinic-2.6.0-SNAPSHOT.jar
      async: 10
      poll: 0
